FAQ = [
{"question": "What is your name?", "answer": "I am a chatbot built by HuuDung!"},
    {"question": "How are you?", "answer": "I'm just a piece of code, but thanks for asking!"},
    {"question": "What can you do?", "answer": "I can chat with you, answer questions, and much more!"},
    {"question": "Tell me a joke.", "answer": "Why don't scientists trust atoms? Because they make up everything!"},
    {"question": "Goodbye", "answer": "Goodbye! Have a nice day!"},
    {"question": "What is Dragon Ball?", "answer": "The Dragon Ball series is a franchise mostly consisting of manga and anime. It revolves around a boy named Son Goku who grows up to become the protector of Earth, along with his allies and his sons, Gohan and Goten."},
    {"question": "Is the anime canon?", "answer": "In Dragon Ball and Dragon Ball Z, the manga is the original canon. The anime is generally not included due to the huge amount of filler. Dragon Ball Z Kai is considered more canon since it stays truer to the manga."},
    {"question": "What about Dragon Ball GT?", "answer": "Dragon Ball GT is considered a side story to the original Dragon Ball Z and has several contradictions with Dragon Ball Super."},
    {"question": "Are the Dragon Ball movies canon?", "answer": "Most Dragon Ball movies are considered a separate canon, with the exception of Dragon Ball Z: Battle of Gods and Dragon Ball Z: Resurrection F."},
    {"question": "How powerful are the characters in Dragon Ball?", "answer": "The Dragon Ball-verse is extremely powerful, ranging from Wall to Island level in the early days to Universe-busting levels in Dragon Ball Super. Characters like Goku, Beerus, and Vegeta can easily destroy a universe."},
    {"question": "How fast are the characters?", "answer": "The characters' speed ranges from Hypersonic in the beginning to MFTL+ (billions to trillions of times faster than light) in the newest media."},
    {"question": "Who is the strongest character?", "answer": "Zen'o is the strongest character in the multiverse, which originally consisted of 18 universes."},
    {"question": "Who is the main character of Dragon Ball?", "answer": "The main character of Dragon Ball is Son Goku, a boy who grows up to become the protector of Earth."},
    {"question": "What is Dragon Ball Z?", "answer": "Dragon Ball Z is a continuation of the original Dragon Ball series, focusing on Goku's adulthood and his battles to protect Earth from powerful foes."},
    {"question": "What is Dragon Ball Z Kai?", "answer": "Dragon Ball Z Kai is a remastered version of Dragon Ball Z, which removes much of the filler content to stay more true to the original manga."},
    {"question": "What is the difference between Dragon Ball Z and Dragon Ball Z Kai?", "answer": "Dragon Ball Z Kai cuts out filler episodes and stays more faithful to the original manga, unlike the original Dragon Ball Z anime."},
    {"question": "Who are Goku's sons?", "answer": "Goku's sons are Gohan and Goten, both of whom inherit their father's fighting spirit and strength."},
    {"question": "What are the levels of power in Dragon Ball?", "answer": "Power levels in Dragon Ball range from Wall level in early series to Universe-busting levels in Dragon Ball Super."},
    {"question": "What are the Saiyan levels?", "answer": "Saiyan levels refer to transformations like Super Saiyan, Super Saiyan 2, and beyond, each greatly increasing the Saiyan's power."},
    {"question": "Who is Beerus?", "answer": "Beerus is the God of Destruction in Universe 7 and is one of the strongest characters in the Dragon Ball universe."},
    {"question": "What is Fusion in Dragon Ball?", "answer": "Fusion is a technique where two characters merge into a single, more powerful being, like Vegito or Gogeta."},
    {"question": "What is the significance of the Dragon Balls?", "answer": "The Dragon Balls are magical orbs that can summon a dragon to grant any wish, playing a central role in the series."},
    {"question": "What are the Dragon Ball video games?", "answer": "There are numerous Dragon Ball video games, which are generally considered separate from the main canon."},
    {"question": "What is Dragon Ball GT?", "answer": "Dragon Ball GT is a sequel to Dragon Ball Z, considered a side story with several contradictions to Dragon Ball Super."},
    {"question": "What is Dragon Ball Super?", "answer": "Dragon Ball Super is the official continuation of Dragon Ball Z, introducing new characters and power levels beyond the original series."},
    {"question": "Who is Frieza?", "answer": "Frieza is one of the main antagonists in Dragon Ball Z, a tyrant who can destroy entire planets and has several transformations."},
    {"question": "What is the Tournament of Power?", "answer": "The Tournament of Power is a multiverse tournament in Dragon Ball Super where teams from different universes fight for survival."},
    {"question": "What is the Hyperbolic Time Chamber?", "answer": "The Hyperbolic Time Chamber is a special room where one year inside equals one day outside, allowing intense training."},
    {"question": "What are Senzu Beans?", "answer": "Senzu Beans are magical beans that can instantly heal injuries and restore energy, often used by Z-Fighters."},
    {"question": "Who is Cell?", "answer": "Cell is a bio-engineered android and one of the main villains in Dragon Ball Z, known for his ability to absorb other beings."},
    {"question": "What is the Buu Saga?", "answer": "The Buu Saga is the final arc of Dragon Ball Z, featuring the ancient, powerful Majin Buu as the main antagonist."},
    {"question": "What is Super Saiyan God?", "answer": "Super Saiyan God is a powerful transformation that Goku achieves in Dragon Ball Super, allowing him to fight on par with gods."},
    {"question": "What are the Namekians?", "answer": "Namekians are an alien race from Planet Namek, known for their abilities to regenerate and create Dragon Balls."},
    {"question": "Who is Vegeta?", "answer": "Vegeta is the prince of the Saiyan race, a rival to Goku, and eventually one of Earth's greatest defenders."},
    {"question": "What is Ultra Instinct?", "answer": "Ultra Instinct is a powerful state that Goku achieves in Dragon Ball Super, allowing him to react without thinking."},
    {"question": "Who is Trunks?", "answer": "Trunks is the son of Vegeta and Bulma, known for traveling back in time to warn the Z-Fighters of future dangers."},
    {"question": "What is the Galactic Patrol?", "answer": "The Galactic Patrol is an intergalactic law enforcement agency in Dragon Ball Super, responsible for maintaining peace in the universe."},
    {"question": "What is Instant Transmission?", "answer": "Instant Transmission is a technique Goku learned that allows him to teleport instantly to any location by sensing a life force."},
    {"question": "What is the Universe 6 Saga?", "answer": "The Universe 6 Saga in Dragon Ball Super features a tournament between Universe 7 and Universe 6, with Goku and Vegeta facing powerful new opponents."},
    {"question": "What is the Spirit Bomb?", "answer": "The Spirit Bomb is a powerful attack used by Goku, created by gathering energy from all living things on a planet."},
    {"question": "What is Zeno's power?", "answer": "Zeno is the King of All and has the power to erase entire universes from existence, making him the most powerful being in the multiverse."},
    {"question": "Who is Majin Buu?", "answer": "Majin Buu is an ancient, powerful being created by the wizard Bibidi, known for his ability to absorb others and regenerate from any injury."},
{"question": "Who is Gohan?", "answer": "Gohan is the eldest son of Goku and Chi-Chi, known for his immense potential and key role in defeating Cell."},
    {"question": "What is the Kamehameha?", "answer": "The Kamehameha is a signature energy attack used by Goku, learned from Master Roshi, and involves channeling energy into a powerful beam."},
    {"question": "Who is Piccolo?", "answer": "Piccolo is a powerful Namekian warrior and initially an enemy of Goku, who later becomes a close ally and mentor to Gohan."},
    {"question": "What is the Great Ape transformation?", "answer": "The Great Ape transformation is a form that Saiyans with tails can achieve during a full moon, increasing their power tenfold."},
    {"question": "What is the significance of Planet Namek?", "answer": "Planet Namek is home to the Namekians and the original Dragon Balls, and it plays a central role in the Frieza Saga."},
    {"question": "Who is Krillin?", "answer": "Krillin is one of Goku's best friends and a skilled martial artist, known for his bravery despite not being as powerful as the Saiyans."},
    {"question": "What is the Red Ribbon Army?", "answer": "The Red Ribbon Army is a military organization that Goku battles in the original Dragon Ball, later responsible for creating the Androids."},
    {"question": "Who is Master Roshi?", "answer": "Master Roshi, also known as the Turtle Hermit, is Goku's first martial arts master and the creator of the Kamehameha technique."},
    {"question": "What is the Fusion Dance?", "answer": "The Fusion Dance is a technique where two characters, like Goten and Trunks, perform a synchronized dance to fuse into a more powerful being."},
    {"question": "What is Shenron?", "answer": "Shenron is the dragon summoned by gathering all seven Dragon Balls, capable of granting any wish within his power."},
    {"question": "Who is Bulma?", "answer": "Bulma is a brilliant scientist and one of Goku's oldest friends, known for inventing the Dragon Radar and marrying Vegeta."},
    {"question": "What is the Saiyan Saga?", "answer": "The Saiyan Saga is the first major arc in Dragon Ball Z, where Goku and the Z-Fighters face off against the Saiyans, including Vegeta."},
    {"question": "What is the Cell Games?", "answer": "The Cell Games is a martial arts tournament organized by Cell to determine the fate of the Earth, with Gohan eventually defeating him."},
    {"question": "What is Super Saiyan Blue?", "answer": "Super Saiyan Blue is a powerful transformation that combines the strength of Super Saiyan with the godly ki of Super Saiyan God."},
    {"question": "Who is Android 18?", "answer": "Android 18 is one of the androids created by Dr. Gero, who later becomes a Z-Fighter and marries Krillin."},
    {"question": "What is the significance of the Time Chamber?", "answer": "The Hyperbolic Time Chamber allows a year’s worth of training in just one day, crucial for Goku and Gohan's preparation for the Cell Games."},
    {"question": "Who is Majin Vegeta?", "answer": "Majin Vegeta is a form Vegeta takes after being possessed by Babidi, which increases his power but causes inner conflict."},
    {"question": "What is the Spirit Sword?", "answer": "The Spirit Sword is a technique used by Vegito, created from his energy, and used to cut through powerful opponents like Super Buu."},
    {"question": "Who is Whis?", "answer": "Whis is the angelic attendant of Beerus, the God of Destruction, and is one of the most powerful beings in the Dragon Ball universe."},
    {"question": "What is the Galactic King?", "answer": "The Galactic King is the leader of the Galactic Patrol, an organization that upholds peace across the galaxy in Dragon Ball Super."},
    {"question": "What is the Z-Sword?", "answer": "The Z-Sword is a legendary weapon sealed on the Sacred World of the Kais, which Gohan pulls out and trains with in the Buu Saga."},
    {"question": "Who is Broly?", "answer": "Broly is a Saiyan with immense power who appears as a main antagonist in several Dragon Ball movies and later in Dragon Ball Super."},
    {"question": "What is the Tournament of Destroyers?", "answer": "The Tournament of Destroyers is a tournament between Universe 7 and Universe 6, where Goku and Vegeta face new challenges."},
    {"question": "What is Potara Fusion?", "answer": "Potara Fusion is a fusion technique using earrings worn by two characters, permanently merging them into a stronger being like Vegito."},
    {"question": "What is the role of the Kais?", "answer": "The Kais are divine beings responsible for overseeing the universe, with the Supreme Kai being the highest-ranking among them."},
    {"question": "Who is Future Trunks?", "answer": "Future Trunks is the version of Trunks from a dystopian future, where he fights against the Androids and later Goku Black."},
    {"question": "What is Ki?", "answer": "Ki is the life force energy that all characters in Dragon Ball use to perform powerful techniques, such as energy blasts and flight."},
    {"question": "Who is Gotenks?", "answer": "Gotenks is the fusion of Goten and Trunks, known for his playful personality and powerful attacks like the Super Ghost Kamikaze Attack."},
    {"question": "What is the Black Star Dragon Balls?", "answer": "The Black Star Dragon Balls are a more powerful set of Dragon Balls introduced in Dragon Ball GT, capable of granting greater but more dangerous wishes."},
    {"question": "What is the role of the Angels?", "answer": "The Angels, like Whis, are divine beings who serve and guide the Gods of Destruction, and they possess immense knowledge and power."},
{"question": "What is Ultra Instinct?", "answer": "Ultra Instinct is a powerful state that allows a fighter to move and react without thinking, a technique mastered by Goku in Dragon Ball Super."},
    {"question": "Who is Beerus?", "answer": "Beerus is the God of Destruction of Universe 7, known for his immense power and responsibility to maintain balance by destroying planets."},
    {"question": "What is the Dragon Radar?", "answer": "The Dragon Radar is a device invented by Bulma that detects the unique energy signature of Dragon Balls, making them easier to find."},
    {"question": "What is the Spirit Bomb?", "answer": "The Spirit Bomb is a powerful attack where Goku gathers energy from all living beings to create a massive ball of energy to defeat evil."},
    {"question": "Who is King Kai?", "answer": "King Kai is a deity who trains Goku in the afterlife, teaching him techniques like the Spirit Bomb and the Kaio-Ken."},
    {"question": "What is the Kaio-Ken?", "answer": "The Kaio-Ken is a technique taught to Goku by King Kai that multiplies his strength, speed, and senses at the cost of straining his body."},
    {"question": "Who is Dabura?", "answer": "Dabura is the King of the Demon Realm and serves as Babidi's right-hand man during the Buu Saga in Dragon Ball Z."},
    {"question": "What is the Galactic Patrol?", "answer": "The Galactic Patrol is an intergalactic police force that maintains peace across the galaxy, with members like Jaco."},
    {"question": "Who is Tien Shinhan?", "answer": "Tien Shinhan is a skilled martial artist and former rival of Goku, known for his powerful techniques like the Tri-Beam and Solar Flare."},
    {"question": "What is the significance of the Hyperbolic Time Chamber?", "answer": "The Hyperbolic Time Chamber allows warriors to train for a year within just one day in the outside world, crucial for preparing against powerful foes."},
    {"question": "Who is Babidi?", "answer": "Babidi is a dark wizard and the son of Bibidi, responsible for resurrecting Majin Buu and controlling several characters with his magic."},
    {"question": "What is the Battle of Gods?", "answer": "Battle of Gods is a Dragon Ball Z movie where Goku faces Beerus, the God of Destruction, and first attains the Super Saiyan God form."},
    {"question": "Who is Yajirobe?", "answer": "Yajirobe is a human samurai known for his love of food and for helping Goku's team, notably by cutting off Vegeta's tail during the Saiyan Saga."},
    {"question": "What is the Power Pole?", "answer": "The Power Pole is a magical staff given to Goku by his grandfather, Gohan, which can extend to incredible lengths."},
    {"question": "Who is Mr. Satan?", "answer": "Mr. Satan, also known as Hercule, is a martial artist who is hailed as the world's champion, despite his actual strength being much lower than the Z-Fighters."},
    {"question": "What is Instant Transmission?", "answer": "Instant Transmission is a teleportation technique Goku learned on Planet Yardrat, allowing him to travel instantly to any location by locking onto a ki signature."},
    {"question": "Who is King Cold?", "answer": "King Cold is the father of Frieza and Cooler, known for his immense power and influence over the universe."},
    {"question": "What is the significance of the World Martial Arts Tournament?", "answer": "The World Martial Arts Tournament is a prestigious event where the strongest fighters compete, serving as the setting for many iconic battles in Dragon Ball."},
    {"question": "Who is Chi-Chi?", "answer": "Chi-Chi is the wife of Goku and the mother of Gohan and Goten, known for her strong-willed personality and dedication to her family."},
    {"question": "What is the Red Potara?", "answer": "Red Potara is a powerful item in Dragon Ball video games that gives characters a significant boost in abilities, often used in special modes."},
    {"question": "Who is Kami?", "answer": "Kami is the Guardian of Earth before Dende, responsible for creating the Earth's Dragon Balls and maintaining balance on the planet."},
    {"question": "What is the Saiyan tail?", "answer": "The Saiyan tail is a unique trait of Saiyans that allows them to transform into Great Apes, but it's also a vulnerability if grabbed or cut."},
    {"question": "Who is Raditz?", "answer": "Raditz is Goku's older brother and the first Saiyan introduced in Dragon Ball Z, who reveals Goku's true heritage as a Saiyan."},
    {"question": "What is the significance of Other World?", "answer": "Other World is the afterlife realm in Dragon Ball where deceased characters go, and where Goku trains under King Kai and other deities."},
    {"question": "Who is Videl?", "answer": "Videl is the daughter of Mr. Satan and Gohan's wife, known for her martial arts skills and eventually learning to fly using ki."},
    {"question": "What is the Garlic Jr. Saga?", "answer": "The Garlic Jr. Saga is a filler arc in Dragon Ball Z where Garlic Jr. returns to take revenge on Goku and his friends after escaping the Dead Zone."},
    {"question": "Who is Majin Buu?", "answer": "Majin Buu is an ancient and powerful creature created by Bibidi, known for his ability to absorb others and his various forms, from Fat Buu to Kid Buu."},
    {"question": "What is the Universe 6 Tournament?", "answer": "The Universe 6 Tournament is a competition between Universe 6 and Universe 7 fighters, where Goku and Vegeta face off against new opponents like Hit."},
    {"question": "Who is Zarbon?", "answer": "Zarbon is one of Frieza's top soldiers, known for his elegance and the ability to transform into a more powerful and monstrous form."},
    {"question": "What is the role of the Elder Kai?", "answer": "The Elder Kai is a former Supreme Kai sealed in the Z-Sword, who later helps Gohan unlock his potential during the Buu Saga."},
    {"question": "What is the Super Dragon Balls?",
     "answer": "The Super Dragon Balls are planet-sized Dragon Balls created by the Dragon God Zalama, capable of granting any wish without limitations."},
    {"question": "Who is Jiren?",
     "answer": "Jiren is a member of the Pride Troopers from Universe 11, known for his immense strength that surpasses even the gods of destruction."},
    {"question": "What is the Tournament of Power?",
     "answer": "The Tournament of Power is a battle royale between teams from eight universes, held by the Omni-Kings, where the losing universes are erased."},
    {"question": "Who is Master Roshi?",
     "answer": "Master Roshi is a legendary martial arts master who trained Goku, Krillin, and many others, and is known for his Kamehameha technique."},
    {"question": "What is the Kamehameha?",
     "answer": "The Kamehameha is a powerful energy wave attack invented by Master Roshi and used frequently by Goku and his allies."},
    {"question": "Who is Majin Vegeta?",
     "answer": "Majin Vegeta is the form Vegeta takes after allowing himself to be possessed by Babidi to gain more power, though he retains control of his mind."},
    {"question": "What is the significance of Namekian Dragon Balls?",
     "answer": "Namekian Dragon Balls are larger and more powerful than Earth's Dragon Balls, able to grant three wishes when summoned."},
    {"question": "Who is Shenron?",
     "answer": "Shenron is the Eternal Dragon summoned by gathering all seven Dragon Balls, capable of granting any wish within his power."},
    {"question": "What is Fusion?",
     "answer": "Fusion is a technique that allows two characters to merge into a single, more powerful being, such as Gotenks or Vegito."},
    {"question": "Who is Pan?",
     "answer": "Pan is the daughter of Gohan and Videl, and the granddaughter of Goku, showing potential as a strong fighter even at a young age."},
    {"question": "What is the Z-Sword?",
     "answer": "The Z-Sword is a powerful weapon said to be unbreakable, but it is eventually broken, revealing the Elder Kai who was sealed inside."},
    {"question": "Who is Android 21?",
     "answer": "Android 21 is a character from the Dragon Ball FighterZ game, a bio-engineered being with a split personality, one of which is malevolent."},
    {"question": "What is the significance of the Saiyan Saga?",
     "answer": "The Saiyan Saga is the first major arc in Dragon Ball Z, introducing powerful Saiyan warriors like Vegeta and Nappa to Earth."},
    {"question": "Who is Captain Ginyu?",
     "answer": "Captain Ginyu is the leader of the Ginyu Force, known for his ability to switch bodies with others using his Body Change technique."},
    {"question": "What is the Hyperbolic Time Chamber?",
     "answer": "The Hyperbolic Time Chamber is a special room where one year inside equals only one day outside, used for intense training."},
    {"question": "Who is Whis?",
     "answer": "Whis is the angelic attendant and martial arts teacher of Beerus, the God of Destruction, and is one of the strongest beings in the universe."},
    {"question": "What is the Great Ape transformation?",
     "answer": "The Great Ape transformation occurs when a Saiyan with a tail looks at the full moon, increasing their power tenfold."},
    {"question": "Who is Trunks?",
     "answer": "Trunks is the son of Vegeta and Bulma, known for his swordsmanship and his role in saving the future from the Androids."},
    {"question": "What is the significance of Senzu Beans?",
     "answer": "Senzu Beans are magical beans that fully restore health and stamina, used by the Z-Fighters to recover from injuries."},
    {"question": "Who is Frieza?",
     "answer": "Frieza is a tyrannical emperor of the universe, known for his cruelty and multiple transformations that increase his power."},
    {"question": "What is the Potara Fusion?",
     "answer": "Potara Fusion is a method of fusion using Potara earrings, which permanently merges two individuals into one, like Vegito."},
    {"question": "Who is Zeno?",
     "answer": "Zeno, or the Omni-King, is the supreme ruler of all universes, with the power to erase entire universes with a thought."},
    {"question": "What is the Dragon Fist?",
     "answer": "The Dragon Fist is a powerful attack used by Goku, where he channels his energy into the form of a golden dragon that pierces through his enemies."},
    {"question": "Who is Cooler?",
     "answer": "Cooler is Frieza's older brother, who also has the ability to transform and seeks to defeat Goku to restore his family's honor."},
    {"question": "What is the role of Dende?",
     "answer": "Dende is a Namekian who becomes the Guardian of Earth after Kami, responsible for creating the Earth's Dragon Balls and healing others."},
    {"question": "Who is Nappa?",
     "answer": "Nappa is a Saiyan warrior and Vegeta's partner, known for his brute strength and ruthless tactics during the Saiyan Saga."},
    {"question": "What is the significance of King Yemma?",
     "answer": "King Yemma is the ruler of the Other World's check-in station, deciding whether souls go to Heaven or Hell."},
    {"question": "Who is Android 18?",
     "answer": "Android 18 is a powerful cyborg created by Dr. Gero, who later marries Krillin and becomes a key ally of the Z-Fighters."},
    {"question": "What is the Destructo Disc?",
     "answer": "The Destructo Disc is a razor-sharp energy disc attack used by Krillin, known for its ability to cut through nearly anything."},
    {"question": "Who is Piccolo?",
     "answer": "Piccolo is a Namekian warrior and former enemy of Goku, who later becomes one of Earth's greatest protectors and Gohan's mentor."},
    {"question": "What is the Final Flash?",
     "answer": "The Final Flash is a powerful energy attack used by Vegeta, one of his signature moves that can cause massive destruction."},
    {"question": "Who is Supreme Kai?",
     "answer": "The Supreme Kai is a god who oversees the entire universe, playing a crucial role during the Buu Saga in Dragon Ball Z."},
    {"question": "What is the Hellzone Grenade?",
     "answer": "The Hellzone Grenade is a technique used by Piccolo where he surrounds his opponent with energy blasts and detonates them simultaneously."},
    {"question": "Who is Yamcha?",
     "answer": "Yamcha is a former desert bandit who becomes one of Goku's allies, known for his Wolf Fang Fist technique and unfortunate defeats."},
    {"question": "What is the Solar Flare?",
     "answer": "The Solar Flare is a technique that blinds opponents with a flash of light, used by various characters like Tien and Krillin."},
    {"question": "Who is Future Trunks?",
     "answer": "Future Trunks is an alternate version of Trunks from a dystopian future, known for his battles against the Androids and Cell."},
    {"question": "What is the Big Bang Attack?",
     "answer": "The Big Bang Attack is a powerful energy blast used by Vegeta, designed to annihilate his enemies in a single shot."},
    {"question": "Who is Goten?",
     "answer": "Goten is the second son of Goku and Chi-Chi, who looks almost identical to his father and achieves Super Saiyan at a young age."},
    {"question": "What is the Instant Kamehameha?",
     "answer": "The Instant Kamehameha is a variation of the Kamehameha used by Goku, where he teleports directly in front of his opponent before firing."},
    {"question": "Who is the Grand Priest?",
     "answer": "The Grand Priest is one of the most powerful beings in the multiverse, serving as the father of the angels and Zeno's attendant."},
    {"question": "What is the Final Kamehameha?",
     "answer": "The Final Kamehameha is a fusion of the Final Flash and Kamehameha techniques, used by Vegito in battle."},
    {"question": "Who is Goku Black?",
     "answer": "Goku Black is a villain in Dragon Ball Super, revealed to be Zamasu in Goku's body, with a deep hatred for mortals."},
    {"question": "What is the Mafuba?",
     "answer": "The Mafuba, or Evil Containment Wave, is a technique used to seal evil entities in a container, often at the cost of the user's life."},
    {"question": "Who is Buu?",
     "answer": "Buu is a magical being created by Bibidi, with various forms like Fat Buu, Evil Buu, and Kid Buu, each with different personalities and powers."},
    {"question": "What is the Neo Tri-Beam?",
     "answer": "The Neo Tri-Beam is an advanced version of the Tri-Beam used by Tien, capable of delivering massive damage even against stronger opponents."},
]